FROM python:3.8

RUN apt update
RUN apt install -y python3-dev gcc

ADD requirements.txt requirements.txt
ADD demo_st.py demo_st.py

# Install required libraries
RUN pip install -r requirements.txt
COPY . /app

# Run it once to trigger resnet download
# RUN python demo_st.py

EXPOSE 8008

# Start the server
# CMD ["python", "demo_st.py", "serve"]
CMD streamlit run app.py